FROM node AS build
WORKDIR /app
ENV PATH ./node_modules/.bin:$PATH
COPY package.json .
RUN yarn

COPY . .

RUN yarn build

FROM nginx
COPY --from=build /app/nginx/nginx.conf /etc/nginx/
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
